linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - typecheck
    - unused
    - gosec
#    - golint
    - goimports
  disable:
    - ineffassign
    - dupl
    - godox
    - bodyclose # too many false negatives

linters-settings:
  goimports:
    local-prefixes: github.com/ory

run:
  skip-dirs:
    - sdk/
  skip-files:
    - ".+_test.go"
    - "corpx/faker.go"

# fandom-start
issues:
  exclude-rules:
    - linters:
      - staticcheck
      text: "SA1019:"
# fandom-end
