courier:
  smtp:
    connection_uri: smtp://kratos-maildev:1025/?skip_ssl_verify=false
hashers:
  argon2:
    iterations: 1
    key_length: 16
    memory: 512MB
    parallelism: 1
    salt_length: 16
identity:
  default_schema_url: file://.config/identity.default.schema.json
log:
  format: json
  leak_sensitive_values: true
  level: debug
selfservice:
  default_browser_return_url: /fandom-auth/
  flows:
    error:
      ui_url: /fandom-auth/error
    login:
      lifespan: 10m
      ui_url: /fandom-auth/auth/login
    logout:
      after:
        default_browser_return_url: https://services.fandom-dev.pl/fandom-auth/auth/login
    recovery:
      enabled: true
      ui_url: https://services.fandom-dev.pl/fandom-auth/recovery
    registration:
      after:
        password:
          hooks:
            - hook: session
      lifespan: 10m
      ui_url: https://services.fandom-dev.pl/self-service/auth/registration
    settings:
      privileged_session_max_age: 15m
      ui_url: https://services.fandom-dev.pl/self-service/settings
    verification:
      after:
        default_browser_return_url: https://services.fandom-dev.pl/self-service/
      enabled: true
      ui_url: https://services.fandom-dev.pl/self-service/verification
  methods:
    link:
      enabled: true
    password:
      enabled: true
  whitelisted_return_urls:
    - https://services.fandom-dev.pl/self-service
serve:
  admin:
    base_url: https://services.fandom-dev.pl/kratos-admin/
    port: 4434
  public:
    base_url: https://services.fandom-dev.pl/kratos/
    cors:
      enabled: true
    port: 4433
session:
  cookie:
    domain: .fandom-dev.pl
dsn: mysql://fauth_admin:6Whv7zQ45qRrZwdpyK@tcp(geo-db-dev-db-master.query.consul:3306)/fandom_auth?max_conns=10&max_idle_conns=2
